// @generated by elbmesh-core v0.1.0
// capability_schema_id: capabilities.elbmesh.v1 v1
// manifest_schema_id: manifest.elbmesh.v1 v1
// manifest_hash: fnv1a64:6a2d2e43edfa832f
// Binding stubs declare types and schema constants only.
// Behavior, provider registration, NATS adapters, and Restate execution are not generated here.

pub mod resources {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Offer;

    impl Offer {
        pub const RESOURCE_TYPE: &'static str = "offer";
        pub const SCHEMA_ID: &'static str = "resource.offer.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct OfferTermsComponent;

    impl OfferTermsComponent {
        pub const COMPONENT_TYPE: &'static str = "offer_terms";
        pub const SCHEMA_ID: &'static str = "component.offer_terms.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}

pub mod actions {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SendOfferEmailAction;

    impl SendOfferEmailAction {
        pub const ACTION_TYPE: &'static str = "send_offer_email";
        pub const RESOURCE_TYPE: &'static str = "offer";
        pub const SCHEMA_ID: &'static str = "action.send_offer_email.v1";
        pub const SCHEMA_VERSION: u32 = 1;
        pub const EMITTED_EVENT_TYPES: &'static [&'static str] = &["offer_created"];
        pub const EXTERNAL_OPERATION_TYPES: &'static [&'static str] = &["lexoffice_create_invoice"];
    }
}

pub mod events {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct OfferCreatedEvent;

    impl OfferCreatedEvent {
        pub const EVENT_TYPE: &'static str = "offer_created";
        pub const RESOURCE_TYPE: &'static str = "offer";
        pub const SCHEMA_ID: &'static str = "event.offer_created.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}

pub mod reactions {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct OfferCreatedToSendOfferEmailReaction;

    impl OfferCreatedToSendOfferEmailReaction {
        pub const REACTION_TYPE: &'static str = "offer_created_to_send_offer_email";
        pub const TRIGGER_EVENT_TYPE: &'static str = "offer_created";
        pub const TARGET_ACTION_TYPE: &'static str = "send_offer_email";
        pub const SCHEMA_ID: &'static str = "reaction.offer_created_to_send_offer_email.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}

pub mod views {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct OfferSummaryView;

    impl OfferSummaryView {
        pub const VIEW_TYPE: &'static str = "offer_summary";
        pub const SCHEMA_ID: &'static str = "view.offer_summary.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}

pub mod queries {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct GetOfferSummaryQuery;

    impl GetOfferSummaryQuery {
        pub const QUERY_TYPE: &'static str = "get_offer_summary";
        pub const SCHEMA_ID: &'static str = "query.get_offer_summary.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}

pub mod external_operations {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LexofficeCreateInvoiceExternalOperation;

    impl LexofficeCreateInvoiceExternalOperation {
        pub const OPERATION_TYPE: &'static str = "lexoffice_create_invoice";
        pub const SCHEMA_ID: &'static str = "external_operation.lexoffice_create_invoice.v1";
        pub const SCHEMA_VERSION: u32 = 1;
    }
}
